# Nome do executável
TARGET = main

# Arquivos fonte
SRCS =  main.c dijkstra.c

# Compilador
CC = gcc

# Flags de compilação
CFLAGS = -Wall -Wextra -pedantic -o $(TARGET)


all:
	$(CC) $(CFLAGS) $(SRCS)

run:
	./$(TARGET)